services:
    router:
      build: .
      container_name: router
      ports: 
        - "80:80"
        - "443:443"
      environment:
        - ADMINEMAIL
        - HOSTDOMAIN
        - PRODUCTION
        - CERT_SERVER
      volumes:
        - "letsencrypt:/etc/letsencrypt"
        - "generatedconfig:/etc/nginx/conf.d/generated/"
      image: lucas42/lucos_router:${ARCH}-latest
      restart: always

volumes:
  generatedconfig:
  letsencrypt: