version: 2.1
orbs:
  lucos: lucos/deploy@0
workflows:
  version: 2
  build-deploy:
    jobs:
      - lucos/build-amd64:
          context: docker
      - lucos/build-arm:
          context: docker
      - lucos/deploy-valen:
          context: docker
          requires:
            - lucos/build-amd64
          filters:
            branches:
              only:
                - main
      - lucos/deploy-xwing:
          context: docker
          requires:
            - lucos/build-arm
          filters:
            branches:
              only:
                - main