version: 2.1
orbs:
  lucos: lucos/deploy@0
workflows:
  version: 2
  build-deploy:
    jobs:
      - lucos/build-amd64
      - lucos/build-armv7l
      - lucos/deploy-avalon:
          requires:
            - lucos/build-amd64
          filters:
            branches:
              only:
                - main
      - lucos/deploy-xwing:
          requires:
            - lucos/build-armv7l
          filters:
            branches:
              only:
                - main